#   _____                     _ _               _____  ______ _______ ____
#  / ____|                   | (_)             |  __ \|  ____|__   __|  _ \
# | |  __ _   _  __ _ _ __ __| |_  __ _ _ __   | |__) | |__     | |  | |_) |
# | | |_ | | | |/ _` | '__/ _` | |/ _` | '_ \  |  _  /|  __|    | |  |  _ <
# | |__| | |_| | (_| | | | (_| | | (_| | | | | | | \ \| |       | |  | |_) |
#  \_____|\__,_|\__,_|_|  \__,_|_|\__,_|_| |_| |_|  \_\_|       |_|  |____/
#
#
# Created by: MrUniverse44
# Sponsor: WHost.es
# SpigotMC Link: https://www.spigotmc.org/resources/88817/
#
settings:
  # This is the gameName of this server
  gameName: 'Game1'
  # This is the game for the server
  gameConfigName: '<notSet>'
  # Enable Check update when the plugin load
  update-check: true
  # Plugin language file, if you want add your custom lang file you need put the name ("messages_<code>.yml") and in the language you put the code, example:
  # messages_en.yml | code: en | language: en
  # messages_es.yml | code: es | language: es
  language: en
  # Server Worlds (The plugin will loads this world on server-startUp)
  worlds:
    - 'gameWorld1'
  # Leave Commands
  leaveCMDs:
    - /leave
    - /quit
    - /salir
  # Plugin Date Format
  dateFormat: 'dd/MM/yyyy'
  # Leave Cancel Time (In Seconds)
  leaveCancelTime: 3
  # Point System
  pointSystem:
    # Runner Points
    runners:
      # Runner death
      death: -6
      # Runner Win
      win: 4
      # Runner kill
      kill: 2
    # Beast Points
    beasts:
      # Beast death
      death: -4
      # Beast Win
      win: 4
      # Beast Kill
      kill: 1
  # Custom Tags
  tags:
    # Runners
    runners:
      toggle: true
      tag: '&b&lRUNNER'
    # Beasts
    beasts:
      toggle: true
      tag: '&e&lBEAST'
    # Killers
    killer:
      toggle: true
      tag: '&a&lKILLER'
  # Status
  status:
    # Behind Blocks
    blocks:
      # Toggle this system
      toggle: false
      # Preparing Block
      preparing: 'STAINED_GLASS:11'
      # Waiting Block
      waiting: 'STAINED_GLASS:5'
      # Starting Block
      starting: 'STAINED_GLASS:4'
      # Playing Block
      playing: 'STAINED_GLASS:14'
      # InGame Block
      InGame: 'STAINED_GLASS:14'
      # Ending Block
      ending: 'STAINED_GLASS:0'
    # Color Status
    color:
      preparing: '&5Config'
      waiting: '&aWaiting'
      starting: '&eStarting'
      playing: '&cPlaying'
      InGame: '&4InGame'
      ending: '&9Restarting'
    # Names
    names:
      preparing: Preparing
      waiting: Waiting
      starting: Starting
      playing: Playing
      InGame: InGame
      ending: Restarting
  # Game Options
  game:
    # Show Buttons message (PlayAgain, AutoPlay, Leave) on game-end
    show-game-buttons-on-end: false
    # Show Beast distance in a actionbar or BossBar
    beastDistance:
      # Toggle
      toggle: true
      #ShowBeast distance formats:
      # - ACTIONBAR (ACTION_BAR,ACTION BAR)
      # - BOSSBAR (BOSS BAR,BOSS_BAR)
      Format: BOSSBAR
    # Command System
    commands:
      # Toggle this system
      toggle: true
      # type of system
      type: WHITELIST
      # list of all commands
      list:
        - 'leave'
        - 'salir'
        - 'rftb'
        - 'grftb'
        - 'lobby'
        - 'hub'
        - 'exit'
    # Game actions
    game-actions:
      # These actions will be executed at the end of the game
      win-actions:
        # Toggle this option
        toggle: false
        # Actions
        values:
          - '<console>eco give <player_name> 100'
      # These actions will be executed at the end of the game
      end-actions:
        # Toggle this option
        toggle: false
        # Actions
        values:
          - '<actionbar>&aWell played!'
      # These actions will be executed at the end of the game
      restart-actions:
        # Toggle this option
        toggle: false
        # Actions
        values:
          - '<actionbar>&bGood Luck for your next game!'
      # These actions will be executed at the start of the game
      start-actions:
        # Toggle this option
        toggle: false
        # Actions
        values:
          - '<msg>&a&lGood Luck!'
      # These actions will be executed at the beast-selection of the game
      selected-beast-actions:
        # Toggle this option
        toggle: false
        # Actions
        values:
          - '<actionbar>&c<arena_beast> was selected!'
    # Game Roles
    roles:
      beast: Beast
      beasts: Beasts
      runner: Runner
      runners: Runners
      killer: Killer
      killers: Killers
    # Game Modes
    modes:
      DOUBLE_BEAST: Double Beast
      CLASSIC: Classic
      INFECTED: Infected
      KILLER: Killer Mode
      ISLAND_OF_THE_BEAST: Island of the beast
      ISLAND_OF_THE_BEAST_DOUBLE: Island of the beast Double
      ISLAND_OF_THE_BEAST_KILLER: Island of the beast Killer
      HISTORY_MODE: History Mode
  # Time Option
  timer:
    weeks: weeks
    week: week
    days: days
    day: day
    minutes: minutes
    minute: minute
    seconds: seconds
    second: second


